### ISSUE TITLE
Support for `quarto`

### ISSUE THREAD

**Issue by shamindras** [bearloga/wikipediapreview-r#3]
Hi @bearloga,

Many thanks for creating this wonderful package. I have recently switched [my blog](https://www.shamindras.com/posts.html) from [`distill`](https://rstudio.github.io/distill/blog.html) to [`quarto`](https://quarto.org/docs/websites/website-blog.html).
So my blog post files have switched from `Rmd` to `qmd` files.
 
I tried to re-render [this blog post](https://www.shamindras.com/posts/2021-12-31-shrotriya2021normtriconvexity/) using the `wikipediapreview` package. Here is [the change](https://github.com/shamindras/ss_personal_quarto_blog/blob/main/posts/2021-12-31-shrotriya2021normtriconvexity/index.qmd#L20-L22) in source file I made, and [an example](https://github.com/shamindras/ss_personal_quarto_blog/blob/main/posts/2021-12-31-shrotriya2021normtriconvexity/index.qmd#L85) of a link I changed. It does not seem to render in the main blog post with the Wikipedia Context Cards however. 

Is there a mistake I'm making in using this package for the `qmd` files?

P.S.
You had kindly helped me [previously manually implement](https://github.com/shamindras/ss_personal_distill_blog/blob/master/_posts/2021-12-31-shrotriya2021normtriconvexity/shrotriya2021normtriconvexity.Rmd#L37-L56) such wikipedia context cards in the equivalent `distill` blogpost, which is now replaced by this `quarto` blogpost.

**Comment by bearloga** [comment]
Hi @shamindras you're very welcome! :)

The issue is that you're suppressing the initialization with `include=FALSE` in the chunk options.

````
```{r setup_01_01, echo=FALSE, results='asis'}
wikipediapreview::wp_init(use_unpkg = TRUE, use_alt_style = TRUE)
```
````

works in Quarto

**Comment by shamindras** [comment]
@bearloga - you are absolutely right - just tested removing `include=FALSE`, and the wiki link preview works.

Thanks again for this cool package and your kind help 👍🏾 !

P.S.
A suggestion, it may be useful to now add `quarto` to the list of _tested_ use cases for your awesome package in your [README](https://github.com/bearloga/wikipediapreview-r#wikipediapreview).

**Comment by bearloga** [comment]
Thanks for the suggestion! I documented more formats, including `quarto`

**Comment by shamindras** [comment]
Super - thanks again!
